name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login
      run: |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}   
    - name: Buildx oraclelinux9-gcc-11.2.1
      run: |       
        docker buildx build --push --platform linux/amd64,linux/arm64 --tag krandalf75/devtools:oraclelinux9-gcc-11.2.1 oraclelinux9-gcc-11.2.1/
    - name: Build debian-gcc-10
      run: |
        docker build  debian-gcc-10/ --tag krandalf75/devtools:debian-gcc-10
        docker image push krandalf75/devtools:debian-gcc-10
    - name: Build  centos-gcc-7.3.1
      run: |
        docker build  centos-gcc-7.3.1/ --tag krandalf75/devtools:centos-gcc-7.3.1
        docker image push krandalf75/devtools:centos-gcc-7.3.1
    
